#include <ADS131M08.h>

/*
 * Example: BasicRead.ino
 * 
 * This example demonstrates how to initialize the ADS131M08 ADC 
 * using the ESP32 to generate the Master Clock (MCLK).
 * It reads all 8 channels and prints the voltage of Channel 0 to Serial.
 *
 * Pin Connections (ESP32-S3):
 *   MCLK  -> GPIO 4
 *   CS    -> GPIO 10
 *   DRDY  -> GPIO 9
 *   MOSI  -> GPIO 11
 *   MISO  -> GPIO 13
 *   SCLK  -> GPIO 12
 */

// Pin Definitions
#define CLK_PIN  4  // MCLK generated by ESP32 LEDC
#define CS_PIN   10
#define DRDY_PIN 9
#define MOSI_PIN 11
#define MISO_PIN 13
#define SCLK_PIN 12

// Initialize Driver
ADS131M08 adc(CLK_PIN, CS_PIN, DRDY_PIN, MOSI_PIN, MISO_PIN, SCLK_PIN);

void setup() {
    Serial.begin(115200);
    while (!Serial) delay(10); // Wait for Serial monitor

    Serial.println("Starting ADS131M08 Basic Read Example");
    
    // Start ADC and Clock
    adc.begin();
    
    Serial.println("ADS131M08 Initialized. Waiting for data...");
}

void loop() {
    // Check if Data Ready pin is active (LOW)
    if (adc.isDataReady()) {
        ADS131Data data;
        
        // Attempt to read data frame
        if (adc.readData(data)) {
            // Convert raw 24-bit integer to Voltage logic
            float voltageCh0 = ADS131M08::rawToVoltage(data.ch[0]);
            
            // Print Channel 0 Voltage
            Serial.printf("CH0: %.4f V\tRaw: %d\n", voltageCh0, data.ch[0]);
            
            // Note: To read other channels, access data.ch[1] through data.ch[7]
        }
    }
}
